// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ID_CGvXOHRK-ya0HXPjYtmHAeXf5ySA',
    appId: '1:659296510115:web:9ec209b429e5a2e1e1df16',
    messagingSenderId: '659296510115',
    projectId: 'hcmus-lettutor',
    authDomain: 'hcmus-lettutor.firebaseapp.com',
    storageBucket: 'hcmus-lettutor.appspot.com',
    measurementId: 'G-W225T1719Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC23KlLYygdmi6H6cQPn5ghb3QhVZchCPQ',
    appId: '1:659296510115:android:3467a201679269a0e1df16',
    messagingSenderId: '659296510115',
    projectId: 'hcmus-lettutor',
    storageBucket: 'hcmus-lettutor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASTSEubXJB33shSabgInw7UGG3-oxJNr4',
    appId: '1:659296510115:ios:df14a98e2cc84c54e1df16',
    messagingSenderId: '659296510115',
    projectId: 'hcmus-lettutor',
    storageBucket: 'hcmus-lettutor.appspot.com',
    iosBundleId: 'com.example.lettutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASTSEubXJB33shSabgInw7UGG3-oxJNr4',
    appId: '1:659296510115:ios:70fd3023492a6829e1df16',
    messagingSenderId: '659296510115',
    projectId: 'hcmus-lettutor',
    storageBucket: 'hcmus-lettutor.appspot.com',
    iosBundleId: 'com.example.lettutor.RunnerTests',
  );
}
